### ISSUE TITLE
Strip markdown

### ISSUE THREAD

**Issue by ProsperoTheBun** [lunet-io/markdig#104]
Feature Request: 
It would be useful to be able to remove all markdown without converting to HTML. E.g, for a preview of a blog's body text.

So an input like ...
```
__Reasons to be happy__
- Sunshine
- Meerkats
- Football
```

Would produce 
```
Reasons to be happy
Sunshine
Meerkats
Football
```

**Comment by ProsperoTheBun** [comment]
FYI, I workaround this on webpages by using jQuery to read the "text" of the element then write it back in. 

```
var text = $("#body-snippet").text();
$("#body-snippet").text(text);
```

But for my app feed API, I'd rather do this server-side.

**Comment by leotsarev** [comment]
Note that's a good practice to sanitize HTML anyway (as markdown parsers do not sanitize). Most of HTML sanitizers could remove all html anyway

**Comment by xoofx** [comment]
> It would be useful to be able to remove all markdown without converting to HTML. E.g, for a preview of a blog's body text.

Markdown at its first origin is text oriented, so that even a simple bullet point list would be readable in plain text. So in your examples above, removing the `-` for the list even for displaying as text is quite an opinionated "preview"... For other markdown elements, I can also see quite different ways to output a text preview (emphasis could remove, but links? still displaying the link or not?...etc.)

Personally don't have time nor special interest in this feature, but a PR is welcome.

Note that `HtmlRenderer` has already a property `EnableHtmlForInline`, that is currently working only for inlines. If someone wants to work on this PR, you can still use the HtmlRenderer, but add a `EnableHtmlForBlock`, and revisit all html block renderers (like the `HeadingRenderer`) and enclose with if/else the portions that are outputing HTML (but keep at least the `WriteLine` to keep a reasonable structure of the text)

**Comment by xoofx** [comment]
Errata about my previous comment: If someone wants to provide such feature, I would much prefer that we do this work as part of #32, as it covers broader use cases.

**Comment by xoofx** [comment]
Actually, scratch that... #32 is probably not ideal either if we want to keep only text... Let me think about this...

**Comment by xoofx** [comment]
So this should be fixed by PR #140 that was just merged to master

**Comment by xoofx** [comment]
So the workaround for this issue is to use a `HtmlRenderer` and setting the `EnableHtmlForInline` to `false`

**Comment by leotsarev** [comment]
I submitted public API facade for this. I wonder if you are open to change like that, I'm happy to expand if required.
