### ISSUE TITLE
Question: Non HTML Output

### ISSUE THREAD

**Issue by wmansfield** [lunet-io/markdig#111]
Before I dig (ha) into this, I'd like to know if its possible to use this to parse MarkDown and generate a custom representation that is not html. (a custom XML that describes the content).  I'd like to essentially create a translation from markdown to a custom 3rd party format.

**Comment by xoofx** [comment]
As you have access to a full AST/syntax model, sure you can query and generate anything from it.

Using the [`Markdown.Parse`](https://github.com/lunet-io/markdig/blob/762196f03b110709fa8906ad2944083f036f8471/src/Markdig/Markdown.cs#L104) that returns directly a `MarkdownDocument` object

Or using the [`Markdown.Convert`](https://github.com/lunet-io/markdig/blob/762196f03b110709fa8906ad2944083f036f8471/src/Markdig/Markdown.cs#L73) which is working with a `IMarkdownRenderer` (e.g The HtmlRenderer is an implementation used for rendering to HTML)

Note that a Markdown AST can still contains HTML syntax node (like for entities `&amp;` or because Markdown allows to have HTML blocks...)

**Comment by wmansfield** [comment]
Thanks for the response. I didn't want to get excited and jump in just to discover a subtle flaw. I'm on it!
