### ISSUE TITLE
Converting to Markdown

### ISSUE THREAD

**Issue by giacomocariello** [lunet-io/markdig#17]
I'm trying to develop an alternative renderer which should produce exactly the same content as the file input. I'm wondering what's the easiest way to represent inter-block whitespace. If every block kept slicing info (start, offset), it would be easier to derive whitespace info.

Could you give me some hint on what could be the best approach?

**Comment by xoofx** [comment]
I'm glad that you would like to add this, as I wanted to do it but didn't have enough time!

The general idea I had was to:

- Add a `Markdown.Normalize()` method
- Add a `ToMarkdownRenderer`
- Implement an `ToMarkdownObjectRenderer` for each block/inlines
- Add these renderers to all extensions

Regarding the inter-block, you cannot rely on the info (start, offset), because the syntax tree could be built by code without a parser. You basically need to have a few rendering options (per block type..etc. it will depend. Typically options like cutting paragraph to a certain width of characters...etc.) and a default behaviour for the spaces we should be CommonMark compliant depending on the block types, so that we can reparse the document and get exactly the same HTML rendering.

So a PR for this would be much welcome! You can start by the core parsers, and progressively we could extend it to all supported extensions.

Let me know if you are interested!

**Comment by giacomocariello** [comment]
Hi Alexandre,
my plan was to add a MarkdownRenderer to allow full or partial normalization, where "partial" would mean that, depending on the renderer configuration, some rendering options may be enforced or may only be considered if no parser info is available. I suppose accessing stringslice info for all the blocks, where available, would allow me to offer this kind of flexibility.

WDYT?

At the moment I've already started writing a simple POC which subclasses TextRendererBase and reimplements core block and inline renderers, just to make some practice.

**Comment by xoofx** [comment]
I would prefer first to focus on a plain normalize that doesn't use the original source document but only the syntax tree.
Let me know your progress, you can open a PR on a fork and I can comment as soon as you feel it starts to be reviewable (even for early direction)

**Comment by madskristensen** [comment]
Can the normalizer take options that lets the caller specify indent size (2 spaces instead of 4 for instance)?

**Comment by giacomocariello** [comment]
Sure.

**Comment by xoofx** [comment]
@giacomocariello do you have a fork with already some code? as I would like to implement this feature asap for MarkdownEditor, otherwise I may start it directly in a new markdig branch, let me know!

**Comment by xoofx** [comment]
Closing this issue as it is now tracked by #155
