### ISSUE TITLE
[Table Extension] Escaped pipe character in code is shown 

### ISSUE THREAD

**Issue by yishengjin1413** [lunet-io/markdig#236]
Hi,

We now have a issue that when escaped pipe in code appear in table. Markdig have different behavior with github. I test on [babelmark](https://babelmark.github.io/?text=%7C++Category+%7C+++Expression++++++%7C++Description++%7C%0A%7C-----------%7C-------------------%7C---------------%7C%0A%7C+D+++++++++%7C+%60x+%5C%7C+y%60++++++++++%7C+++Description+%7C%0A%7C+C+++++++++%7C+*x+%5C%7C+y*++++++++++%7C+++Description+%7C%0A%7C+B+++++++++%7C++x+%5C%7C+y+++++++++++%7C+++Description+%7C%0A%7C+A+++++++++%7C+%60x++%7C+y%60++++++++++%7C+++Description+%7C) and here is the example:

```
|  Category |   Expression      |  Description  |
|-----------|-------------------|---------------|
| D         | `x \| y`          |   Description |
| C         | *x \| y*          |   Description |
| B         |  x \| y           |   Description |
| A         | `x  | y`          |   Description |
```

Markdig result:
<table>
  <thead>
    <tr>
      <th>
        Category
      </th>
      <th>
        Expression
      </th>
      <th>
        Description
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        D
      </td>
      <td>
        <code>x \| y</code>
      </td>
      <td>
        Description
      </td>
    </tr>
    <tr>
      <td>
        C
      </td>
      <td>
        <em>x | y</em>
      </td>
      <td>
        Description
      </td>
    </tr>
    <tr>
      <td>
        B
      </td>
      <td>
        x | y
      </td>
      <td>
        Description
      </td>
    </tr>
    <tr>
      <td>
        A
      </td>
      <td>
        <code>x | y</code>
      </td>
      <td>
        Description
      </td>
    </tr>
  </tbody>
</table>

Github result:

<table>
  <thead>
    <tr>
      <th>
        Category
      </th>
      <th>
        Expression
      </th>
      <th>
        Description
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        D
      </td>
      <td>
        <code>x | y</code>
      </td>
      <td>
        Description
      </td>
    </tr>
    <tr>
      <td>
        C
      </td>
      <td>
        <em>x | y</em>
      </td>
      <td>
        Description
      </td>
    </tr>
    <tr>
      <td>
        B
      </td>
      <td>
        x | y
      </td>
      <td>
        Description
      </td>
    </tr>
    <tr>
      <td>
        A
      </td>
      <td>
        `x
      </td>
      <td>
        y`
      </td>
    </tr>
  </tbody>
</table>

Is it possible for markdig to keep the same behavior with github in this case?

**Comment by Kryptos-FR** [comment]
To me it is actually the GitHub version that is incorrect. Anything inside `` should be verbatim.
Maybe raise a similar issue in the GitHub repository (linking to that one) and let's see what they think of it.

**Comment by xoofx** [comment]
This is a known issue. The previous implementation of tables in Markdown at GitHub was performing a split on the final HTML in order to create the table (!), so they have simply replicated this poor behavior. Unfortunately, they will unlikely change this because they have now a legacy to be compatible with...

This is one question I asked a while ago while implementing tables for markdig, I came with the solution of doing it more properly using the parser information instead of going through text/character split.  The GitHub developer behind the new implementation (cmark fork), gave some insights about [how they implemented the pipe table](https://talk.commonmark.org/t/parsing-strategy-for-tables/2027/46?u=xoofx)

We should probably have an option for GitHub pipe table parser... that would trigger a completely different parser (instead of trying to adapt the current which I would like to kept as it is, as it is more accurate)

**Comment by yishengjin1413** [comment]
Thanks @xoofx , very useful information. I will keep the markdig behavior for now. I think it's more clear too.
