### ISSUE TITLE
Autolink does not show the full text

### ISSUE THREAD

**Issue by yishengjin1413** [lunet-io/markdig#356]
For the following example, Autolink does not show the full text.

```
https://blogs.windows.com/windowsexperience/2017/01/23/Introducing-Windows-Defender-Security-Center/\#m4mv5W0GYKZpGvfA.97
```

[BabelMark result](https://babelmark.github.io/?text=https%3A%2F%2Fblogs.windows.com%2Fwindowsexperience%2F2017%2F01%2F23%2FIntroducing-Windows-Defender-Security-Center%2F%5C%23m4mv5W0GYKZpGvfA.97) :

```
<p>
  <a href="https://blogs.windows.com/windowsexperience/2017/01/23/Introducing-Windows-Defender-Security-Center/#m4mv5W0GYKZpGvfA.97">https://blogs.windows.com/windowsexperience/2017/01/23/Introducing-Windows-Defender-Security-Center/\#m4mv5W0GYKZpGvfA.9</a>
</p>
```

The link url is right but the link text missing the ending `7`.

**Comment by MihaZupan** [comment]
A part of the issue here stems from the differences between the definition of a regular linka and an autolink.
Commonmark states that backslashes will not work in autolinks (but will in links).

@yishengjin1413 As this is an Autolink, this means that the backslash in this case is not discarded but percent-encoded.

I believe the correct HTML for this markdown is
```html
<p><a href="https://blogs.windows.com/windowsexperience/2017/01/23/Introducing-Windows-Defender-Security-Center/%5C#m4mv5W0GYKZpGvfA.97">https://blogs.windows.com/windowsexperience/2017/01/23/Introducing-Windows-Defender-Security-Center/\#m4mv5W0GYKZpGvfA.97</a></p>
```

In your example, the URL `https://blogs.windows.com/windowsexperience/2017/01/23/Introducing-Windows-Defender-Security-Center/%5C#m4mv5W0GYKZpGvfA.97` will not be recognised as valid on the server anymore.

**Comment by yishengjin1413** [comment]
@MihaZupan Make sense. Thanks for your explanation and fixing the bug.
