### ISSUE TITLE
uncorrect parsing result with very rare case

### ISSUE THREAD

**Issue by kflili** [lunet-io/markdig#378]
Two cases:
Hello eudev@**microsoft.**com
Hello benefit of **$**225
![image](https://user-images.githubusercontent.com/19175478/67444899-bb36cc00-f5bf-11e9-9ec6-88b5be2f484a.png)

Please the test link in below.
https://babelmark.github.io/?text=Hello+eudev%40**microsoft.**com%0A%0A+%0AHello+benefit+of+**%24**225

**Comment by xoofx** [comment]
It is correct for all CommonMark implementations and part of the specifications.

**Comment by kflili** [comment]
> CommonMark implementations and part of the specifications

@xoofx Thanks for the reply. Does that mean it meet the markdown standard, and should render as such? Our user want to get parsing upper results, not the lower results in the screenshot.

**Comment by xoofx** [comment]
Yes, it is the standard, so we can't change it.  You can see also that on GitHub it is rendered like Markdig (because now GitHub is using a CommonMark compliant parser)

Hello eudev@**microsoft.**com
Hello benefit of **$**225

> Any work around for this special case?

Apart developing a new emphasis parser by forking the default extension and replacing with your own, there is no easy workaround

**Comment by kflili** [comment]
Thanks @xoofx for the clear answer!
