### ISSUE TITLE
Heading variations

### ISSUE THREAD

**Issue by mhomde** [lunet-io/markdig#76]
I've come across some heading variations that are not picked up by the parser

* Any header where there's no space between # and the heading, for ex:  `#Heading`

* When headers are combined with markdown, ex:` ###**HEADING**`

Not sure if this goes against the spec but would be great if they could be covered somehow

Keep up the good work!

**Comment by xoofx** [comment]
Yes, it is part of the [CommonMark specs: ATX headings](http://spec.commonmark.org/0.27/#atx-headings): _The opening sequence of # characters must be followed by a space or by the end of line._

**Comment by xoofx** [comment]
Note that as github is transitioning to Commonmark, they now follow the same rule:

> #Heading is a plain text

**Comment by mhomde** [comment]
Can I write an extension or something to get around this? Reddit markdown is notoriously sloppy ... :/

**Comment by xoofx** [comment]
Yes, you can. You will have to modify the [HeadingBlockParser](https://github.com/lunet-io/markdig/blob/2c10ac59d3efb9a7821565100e35956767faf0a3/src/Markdig/Parsers/HeadingBlockParser.cs#L65) to add a bool property in order to support this switch (some extensions like [SoftlineBreakAsHardlineExtension](https://github.com/lunet-io/markdig/blob/2c10ac59d3efb9a7821565100e35956767faf0a3/src/Markdig/Extensions/Hardlines/SoftlineBreakAsHardlineExtension.cs) are done like this)
