### ISSUE TITLE
Support for underline and strikethrough?

### ISSUE THREAD

**Issue by markau** [lunet-io/markdig#77]
Sweet library. I am using a very simplistic implementation just to convert basic markdown to html for display on a page.

I am not sure our users will even need this feature, but I noticed some markdown is not being rendered as expected; in this case underline (++) and strikethrough (~\~).

![image](https://cloud.githubusercontent.com/assets/3004849/20963453/52c29c14-bcbd-11e6-9991-2ae2333db18e.png)

I don't know if these are strictly valid markdown tags or not, so this might not actually be an issue with markdig. I thought I would raise it anyway. Cheers!

**Comment by xoofx** [comment]
They are already [supported](https://github.com/lunet-io/markdig/blob/master/src/Markdig/MarkdownExtensions.cs#L364) (check also [babelmark + markdig advanced](https://babelmark.github.io/?text=This+is+a+%2B%2Bunderline%2B%2B+and+~~strikethrough~~))

In order to use them, you need to activate the proper extension on the markdown pipeline:

```csharp
var pipeline = new MarkdownPipelineBuilder().UseEmphasisExtras().Build();
var result = Markdown.ToHtml(input, pipeline);
```

**Comment by markau** [comment]
Ahh, thanks for pointing this out @xoofx !

(And I see strikethrough in the README, oops...!)
