### ISSUE TITLE
Removing of HeadingBlockParser from pipeline.BlockParsers is not affect setext headings

### ISSUE THREAD

**Issue by magicxor** [lunet-io/markdig#83]
I'm trying to make stop markdig from parsing headers (h1-h6).

```
        public static MarkdownPipelineBuilder DisableHeadings(this MarkdownPipelineBuilder pipeline)
        {
            var headingBlockParser = pipeline.BlockParsers.Find<HeadingBlockParser>();
            if (headingBlockParser != null)
            {
                pipeline.BlockParsers.Remove(headingBlockParser);
            }
            return pipeline;
        }
```
But this code doesn't affect [setext headings](https://github.com/lunet-io/markdig/blob/4f52e893eef8401ad7e50f7442c3dc01996f3e91/src/Markdig.Benchmarks/spec.md#setext-headings).
Is it normal behavior? How can I solve this problem?
Thanks.

**Comment by xoofx** [comment]
Unfortunately, disabling setext headings requires an internal change because the parsing is performed inside the [ParagraphBlockParser](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Parsers/ParagraphBlockParser.cs#L74). It is perfectly possible to do it by adding a boolean property on this parser, and provide an extension for it.
